export const SET_FORECAST_DATA = 'SET_FORECAST_DATA';
export const SET_FORECAST_DATA_ERROR = 'SET_FORECAST_DATA_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const CLEAR_USER = 'CLEAR_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
